import {
  breakpoints,
  colors,
  motion,
  radius,
  shadows,
  sizing,
  spacing,
  typography,
} from "@stability/design-tokens";
import type { CSSProperties } from "react";

type ThemeVariables = CSSProperties &
  Record<`--${string}`, string | number | undefined>;

export const webThemeVariables: ThemeVariables = {
  "--color-background-canvas": colors.background.canvas,
  "--color-background-subtle": colors.background.subtle,
  "--color-background-elevated": colors.background.elevated,
  "--color-surface-primary": colors.surface.primary,
  "--color-surface-secondary": colors.surface.secondary,
  "--color-surface-interactive": colors.surface.interactive,
  "--color-text-primary": colors.text.primary,
  "--color-text-secondary": colors.text.secondary,
  "--color-text-muted": colors.text.muted,
  "--color-text-inverse": colors.text.inverse,
  "--color-border-subtle": colors.border.subtle,
  "--color-border-default": colors.border.default,
  "--color-border-strong": colors.border.strong,
  "--color-brand-primary": colors.brand.primary,
  "--color-brand-primary-hover": colors.brand.primaryHover,
  "--color-brand-primary-pressed": colors.brand.primaryPressed,
  "--color-brand-secondary": colors.brand.secondary,
  "--color-brand-subtle": colors.brand.subtle,
  "--color-status-success": colors.status.success,
  "--color-status-warning": colors.status.warning,
  "--color-status-danger": colors.status.danger,
  "--color-status-info": colors.status.info,
  "--color-status-surface-success": colors.statusSurface.success,
  "--color-status-surface-warning": colors.statusSurface.warning,
  "--color-status-surface-danger": colors.statusSurface.danger,
  "--color-status-surface-info": colors.statusSurface.info,
  "--color-focus-ring": colors.focus.ring,
  "--color-overlay-backdrop": colors.overlay.backdrop,
  "--radius-small": `${radius.small}px`,
  "--radius-medium": `${radius.medium}px`,
  "--radius-large": `${radius.large}px`,
  "--radius-full": `${radius.full}px`,
  "--spacing-xs": `${spacing.xs}px`,
  "--spacing-sm": `${spacing.sm}px`,
  "--spacing-md": `${spacing.md}px`,
  "--spacing-lg": `${spacing.lg}px`,
  "--spacing-xl": `${spacing.xl}px`,
  "--spacing-xxl": `${spacing.xxl}px`,
  "--spacing-xxxl": `${spacing.xxxl}px`,
  "--control-small": `${sizing.control.small}px`,
  "--control-medium": `${sizing.control.medium}px`,
  "--control-large": `${sizing.control.large}px`,
  "--content-compact": `${sizing.content.compact}px`,
  "--content-standard": `${sizing.content.standard}px`,
  "--content-wide": `${sizing.content.wide}px`,
  "--breakpoint-compact": `${breakpoints.compact}px`,
  "--breakpoint-medium": `${breakpoints.medium}px`,
  "--breakpoint-expanded": `${breakpoints.expanded}px`,
  "--breakpoint-wide": `${breakpoints.wide}px`,
  "--shadow-subtle": shadows.subtle.web,
  "--shadow-raised": shadows.raised.web,
  "--motion-fast": `${motion.duration.fast}ms`,
  "--motion-normal": `${motion.duration.normal}ms`,
  "--motion-slow": `${motion.duration.slow}ms`,
  "--motion-ambient": `${motion.duration.ambient}ms`,
  "--motion-standard": motion.easing.standard,
  "--motion-emphasized": motion.easing.emphasized,
  ...Object.fromEntries(
    Object.entries(typography).flatMap(([variant, style]) => [
      [`--type-${variant}-size`, `${style.fontSize}px`],
      [`--type-${variant}-line`, `${style.lineHeight}px`],
      [`--type-${variant}-weight`, style.fontWeight],
      [`--type-${variant}-tracking`, `${style.letterSpacing}px`],
    ]),
  ),
};
